comment out options for install

diff --git a/modules/terraform-aws-s3-file-gateway/module/scripts/mount-filegateway b/modules/terraform-aws-s3-file-gateway/module/scripts/mount-filegateway
--- a/modules/terraform-aws-s3-file-gateway/module/scripts/mount-filegateway
+++ b/modules/terraform-aws-s3-file-gateway/module/scripts/mount-filegateway
@@ -6,6 +6,31 @@
 # 2nd arg is the bucket name listed by showmount -e $1 starting without /
 # 3rd args is target path
 
+# eg: ./mount-filegateway 10.1.139.151 rendering.dev.firehawkvfx.com /Volumes/cloud_prod
+
+# function has_yum {
+#   [[ -n "$(command -v yum)" ]]
+# }
+
+# function has_apt_get {
+#   [[ -n "$(command -v apt-get)" ]]
+# }
+
+# function has_brew {
+#   [[ "$OSTYPE" == "darwin"* ]]
+# }
+
+# if $(has_apt_get); then
+#     sudo DEBIAN_FRONTEND=noninteractive apt-get install -y nfs-common
+# elif $(has_yum); then
+#     sudo yum install -y nfs-common
+# elif $(has_brew); then
+#     sudo brew install -y nfs-common
+# else
+#     echo "Could not find apt-get, yum, or brew. Cannot install dependencies on this OS."
+#     exit 1
+# fi
+
 showmount -e "$1"
 
 sudo mkdir -p "$3"
